Add ignore_case argument to element_should_contain 
robotframework/SeleniumLibrary pull request #1034
Opened 2018-01-19 13:32 UTC by SidePlace

2018-01-19 13:34 UTC, SidePlace commented
Trying to help on #849 
Forgot to mention bug ID in the commit message

2018-01-25 21:05 UTC, aaltat commented
Code looks OK, but PR is missing test. PR are not merged without test backing them up.

2018-01-26 15:47 UTC, SidePlace commented
Hi @aaltat I just pushed my tests for it. Let me know if I'm doing something improperly.

2018-01-26 21:27 UTC, aaltat commented
We have had lately problems with the Travis CI, sometimes the test execution stops. It seems that this PR is also suffering from the same problem. I did restart the two failed runs and lets see how it goes.

2018-01-26 22:06 UTC, aaltat requested changes
There are two things to fix.

2018-01-26 22:06 UTC, aaltat commented on test/acceptance/ignoreCase.robot
> +*** Settings ***
There already is a existing suite for this keyword, in ./test/acceptance/keywords/content_assertions.robot You have two options:
1) Move tests from here to the content_assertions suite
2) Move the `Element Should Contain` keyword test all in same and new suite. Also change the suite name to describe the whole keyword, not just the new feature.

2018-01-26 22:06 UTC, aaltat commented on test/acceptance/ignoreCase.robot
> +${ISSUE_URL}      https://github.com/robotframework/SeleniumLibrary/issues/849
Using links to external resources are not allowed. The acceptance test runner starts small http server. which must be used to serve the required html files. Please take an example from the ./test/acceptance/keywords/content_assertions.robot suite. 

The test logic is OK,

2018-01-27 13:14 UTC, aaltat commented
If you want credit for your work, please add your name and short description what you have done in the https://github.com/robotframework/SeleniumLibrary/blob/master/CHANGES.rst

2018-02-12 05:54 UTC, aaltat commented
Closing on favour of #1043.

2018-02-12 05:54 UTC, closed without merging