849 verify text case insensitive
robotframework/SeleniumLibrary pull request #1043
Opened 2018-02-03 02:04 UTC by rubygeek

Added code and tests to resolve  #849

2018-02-03 21:02 UTC, aaltat requested changes
Code generally looks good, expect the code block which we do not usually use. But there should be few more test done before the PR can be merged.

2018-02-03 21:02 UTC, aaltat commented on src/SeleniumLibrary/keywords/element.py
> +
We are not in favor of code blocks. Please remove the empty line from this line and from lines 71 and 76.

2018-02-03 21:02 UTC, aaltat commented on src/SeleniumLibrary/keywords/element.py
>          not a substring.
In new line, add text: ``ignore_case`` argument is new in SeleniumLibrary 3.1.

Please fix in keywords where the new argument is added.

2018-02-03 21:02 UTC, aaltat commented on src/SeleniumLibrary/keywords/element.py
> +
We are not in favor of code blocks. Please remove the empty line from this line and from line 99.

2018-02-03 21:02 UTC, aaltat commented on test/acceptance/keywords/content_assertions.robot
> +
Empty line here is not needed.

2018-02-03 21:02 UTC, aaltat commented on test/acceptance/keywords/content_assertions.robot
>      Element Should Contain    some_id    This text is inside an identified element
Please add line: `| Element Should Contain | some_id | This text is inside an identified element | ignore_case=False |`

2018-02-03 21:02 UTC, aaltat commented on test/acceptance/keywords/content_assertions.robot
> +    Element Should Not Contain    some_id    THIS TEXT is not inside an identified element   ignore_case=False
1) Please add line: `Element Should Not Contain | some_id | This text is not inside an identified element | ignore_case=True |`
2) Please also add new test where `Element Should Not Contain` when `ignore_case`argument is used with True and False values but the keyword fails. In the test use `Run Keyword And Expect Error`to verify that correct error is raised.

2018-02-12 00:49 UTC, rubygeek commented
I have fixed the code according to suggestions and ready for final review.

2018-02-12 05:50 UTC, aaltat approved these changes

2018-02-12 05:53 UTC, merged