Cover element should work as add-blocker.
robotframework/SeleniumLibrary pull request #1236
Opened 2018-11-18 22:51 UTC by SergiuTudos

It should cover elements with dynamic content

2018-11-18 23:12 UTC, SergiuTudos commented
can anyone help me understand why it fails ?

2018-11-18 23:40 UTC, HelioGuilherme66 commented
@SergiuTudos Re-executed the tests and they are green again. Sometimes it happens :(

2018-11-18 23:41 UTC, SergiuTudos commented
Great. Waiting for review

2018-11-19 06:14 UTC, aaltat commented
Could you raise an issue, where your need is explained. Project uses issues to track what goes in to the next release.

By a quick look,  code looks OK, but I need to take a look from a bigger screen. Could you also write a test where element is not found?

2018-11-19 06:17 UTC, aaltat requested changes

2018-11-19 06:17 UTC, aaltat commented on atest/acceptance/keywords/elements.robot
> +    Element Should Not be Visible  //img[@src="image.jpg"]
We should also verify that the `newDiv` is visible. Please also add plank line in the end.

2018-11-19 06:21 UTC, aaltat commented
Also if you want credit for your work add your name to: https://github.com/robotframework/SeleniumLibrary/blob/master/CHANGES.rst

2018-11-19 08:28 UTC, SergiuTudos commented on atest/acceptance/keywords/elements.robot
> +    Element Should Not be Visible  //img[@src="image.jpg"]
I added name="covered"  for that div

2018-11-19 13:00 UTC, aaltat approved these changes

2018-11-19 13:02 UTC, aaltat commented
Thank you for the pull request. The code looks OK from a mobile screen but I need to take a look from a bigger screen before merging the PR.

2018-11-22 09:17 UTC, SergiuTudos commented
Hi,
I don't want to be too insistent, but can you please review this and merge this code. I am going to develop a visual testing approach with Robot. Need to cover dynamic content and Get element screenshot for visual diff.

Thank you

2018-11-22 14:43 UTC, aaltat commented
Sorry that it's taken so long, but there has been personal blockers and I have not found time to look this. But next time I do something with the project, this is the first thing.

2018-11-22 18:41 UTC, aaltat commented
Updated the documentation with few minor fixes and when Travis build is green I will merge the PR to master.

2018-11-22 20:09 UTC, merged