Update travis conf
robotframework/SeleniumLibrary pull request #678
Opened 2016-10-18 05:13 UTC by drobota

@aaltat, @HelioGuilherme66, @pekkaklarck  please, have a look.

2016-10-18 05:43 UTC, ombre42 commented
Increasing minimum version of selenium and also pegging to a specific version? This does not just affect CI but also where this library is installed or did I miss something?

2016-10-18 05:49 UTC, drobota commented
Now selenium 2 library can only work with old Firefox driver which works only in firefox up to version 47.0.1 and selenium 2.53.6. We might need drop supporting it and switch to marionette(https://github.com/mozilla/geckodriver)

2016-10-18 06:04 UTC, ombre42 commented
Understandable but pip can handle having a minimum and maximum version (I.e. range of compatible versions). Usually we try to give flexibility to the end user. Also I think a big change like selenium version should be mentioned in commit message and PR message IMHO.

2016-10-18 18:32 UTC, aaltat commented
It should be possible to modify existing functionality in Open Browser keyword to support Firefox with and without the marionette. Also it should be possible to make the change in such manner that the it doesn't cause changes to the keyword signature.

I am thinking how to handle the change with the grid side. Should the keyword make some automatic setting with the desired capabilities or not. I am starting to think that we should not make any magic when user set the desired capabilities.

Therefore I am against changing the minimum required selenium version. Also the selenium 3 should be only drop in replacement for selenium 2 and it doesn't cause changes to the selenium API.

Of course we should recommended people to use latest selenium but we should not force it.

2016-12-07 12:57 UTC, aaltat requested changes
One think which I do not fully grasp with Travis, where are those browsers opened?  Are they opened by Travis or are they used with SauceLabs? Where those remote_url and the desired_capabilities are coming from?

2016-12-07 12:57 UTC, aaltat commented on .travis.yml
> +matrix:
Should we add some run with Python 3 too. Example have to runs with Chrome one with Python 2.7 and another one with Python 3.

2016-12-07 12:57 UTC, aaltat commented on requirements.txt
> +selenium == 2.53.6
Despite my previous comments, I think this change is OK, specially with the selenium 3. Supporting old version of selenium would need extra runs from the CI and in the current model, we do not have resource to provide the support and we do not have resources to pay for the CI time (or actually pay for the cloud service to get all the browsers running)

2016-12-07 12:57 UTC, aaltat commented on .travis.yml
> +    - secure: "QyY0j8C+hVhsGLv4YU0UMvLm5wBDg6xT5J0Ee77C/JAQ6vcdCMpTfWI8oDxTZb7pBhpDkYuNe747yCYF5PrdBYQbO08FilxctReuJfMXcH44rZC5q49mUmPamkvg1LkzIWuC1s9uKnjlvyDT5ojuPXZl2Vn0gIhSIg+yOyBkM1U="
Are the Sauce Labs hash keys to access the account. You have the clear passwords saved in somewhere? Perhaps we should distribute the password with wider audience but not put the passwords in git repo.

Is there reason why the are two secure lines?

2016-12-07 12:57 UTC, aaltat commented on src/Selenium2Library/keywords/_element.py
> +            .click().perform()
It could be cleaner to write: 
        action = ActionChains(self._current_browser())
        action.move_to_element(element)
        action.move_by_offset(xoffset, yoffset)
        action.click().perform()

2016-12-07 12:57 UTC, aaltat commented on src/Selenium2Library/keywords/_element.py
>          See `Page Should Contain Element` for explanation about `message` and
I think empty line should have not been removed.

2016-12-07 12:57 UTC, aaltat commented on test/acceptance/create_webdriver.robot
> +    [Tags]  Known Issue Chrome    Known Issue Internet Explorer    Known Issue Safari
Should we document the tags we use, so that people contributing could also use them right?

2016-12-07 13:15 UTC, aaltat commented on requirements.txt
> +selenium == 2.53.6
But instead `selenium == 2.53.6` should we say `selenium >= 2.53.6`

2016-12-09 05:45 UTC, drobota commented on .travis.yml
> +    - secure: "QyY0j8C+hVhsGLv4YU0UMvLm5wBDg6xT5J0Ee77C/JAQ6vcdCMpTfWI8oDxTZb7pBhpDkYuNe747yCYF5PrdBYQbO08FilxctReuJfMXcH44rZC5q49mUmPamkvg1LkzIWuC1s9uKnjlvyDT5ojuPXZl2Vn0gIhSIg+yOyBkM1U="
Yes, these are encoded login and password for sauce labs. They can be securely stored in repo because they can be decoded only in travis env.

2016-12-09 05:45 UTC, drobota commented on .travis.yml
> +matrix:
I can add it, but do s2l compatible with py3?

2016-12-10 20:17 UTC, aaltat commented on .travis.yml
> +    - secure: "QyY0j8C+hVhsGLv4YU0UMvLm5wBDg6xT5J0Ee77C/JAQ6vcdCMpTfWI8oDxTZb7pBhpDkYuNe747yCYF5PrdBYQbO08FilxctReuJfMXcH44rZC5q49mUmPamkvg1LkzIWuC1s9uKnjlvyDT5ojuPXZl2Vn0gIhSIg+yOyBkM1U="
OK, this is good to go then.

2016-12-10 20:19 UTC, aaltat commented on .travis.yml
> +matrix:
No it is not yet compatible. But the aim for the 2.0 release, which hopefully is the next release, is to make it compatible with Python 3.

2016-12-10 20:32 UTC, aaltat approved these changes

2016-12-10 20:33 UTC, merged