Fixes Chromedriver tests under Windows, by @yahman72
robotframework/SeleniumLibrary pull request #694
Opened 2016-11-29 22:14 UTC by HelioGuilherme66

(from his commit: webdriver process management)

2016-11-29 22:37 UTC, HelioGuilherme66 commented
Tested under Windows 7 Professional x64 and Python 2.7.12 32bit, selenium 2.53.6, RF 3.0
ChromeDriver  2.25.426923 - Chrome 54.0.2840.99 m - 0 failed tests
InternetExplorerDriver (32-bit) 2.53.1.0 - IE 11.0.31 - 23 failed tests
Firefox 47.0.1 - 0 failed tests
PhantomJS 2.1.1 - 21 failed tests (excluded Choose File test)

2016-11-30 07:32 UTC, aaltat commented
There are few minor things to fix, mostly code cleanup and following pep8. But those things are hard to comment with mobile. I will try to find time to comment the changes later. Could you raise an issue about the problem?

2016-12-03 10:27 UTC, aaltat requested changes

2016-12-03 10:27 UTC, aaltat commented on test/resources/testserver/testserver.py
>  class StoppableHttpRequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
Two empty lines before the class definition

2016-12-03 10:27 UTC, aaltat commented on test/resources/testserver/testserver.py
> +class HttpEchoer(socket._fileobject):
Two empty lines before the class definition

2016-12-03 10:27 UTC, aaltat commented on test/run_tests.py
> +    #server_output = open("server.log", 'w+', buffering=False)
If this is commented out, where the line 51 server_output comes.

2016-12-03 10:27 UTC, aaltat commented on test/resources/testserver/testserver.py
> +        #self.send_header("Connection", "close")
If this is not needed, remove it

2016-12-03 10:27 UTC, aaltat commented on test/resources/testserver/testserver.py
> -
Two empty lines before the class definition

2016-12-03 19:34 UTC, HelioGuilherme66 commented on test/run_tests.py
> +    #server_output = open("server.log", 'w+', buffering=False)
That is just an alternative way to keep the server logs (like Jari explained in initial code/Issue).

2016-12-03 19:35 UTC, HelioGuilherme66 commented
Code is PEP8 compliant now.

2016-12-03 20:26 UTC, aaltat commented on test/run_tests.py
> +    #server_output = open("server.log", 'w+', buffering=False)
OK, need to read it from there.

2016-12-07 13:16 UTC, aaltat commented on test/run_tests.py
> +    #server_output = open("server.log", 'w+', buffering=False)
I did read and looks OK.

2016-12-07 13:21 UTC, aaltat commented on test/run_tests.py
> +    #server_output = open("server.log", 'w+', buffering=False)
But should we remove the comment then

2016-12-07 13:33 UTC, HelioGuilherme66 commented on test/run_tests.py
> +    #server_output = open("server.log", 'w+', buffering=False)
No, we should not remove the comment. We should add a comment describing that by default the output goes to a temporary file, but toggling the commented lines allows developer to keep the output.

2016-12-07 14:05 UTC, aaltat commented on test/run_tests.py
> +    #server_output = open("server.log", 'w+', buffering=False)
I don not like commented code, but adding the doc about the that part is good to go.

2016-12-11 00:03 UTC, HelioGuilherme66 commented on test/run_tests.py
> +    #server_output = open("server.log", 'w+', buffering=False)
Added comment for clarification.

2016-12-11 08:28 UTC, pekkaklarck commented
Commented code makes no sense. If we think server logs are needed, we should write code like that. I think that would be fine, writing them into the same directory as other results shouldn't harm. If we want to make it configurable, we should add a command line option. I doubt it's worth the effort in this case.

2016-12-11 08:31 UTC, pekkaklarck commented
Also, the code is not PEP-8 compliant.

2016-12-11 13:48 UTC, pekkaklarck commented
I changed run_tests.py to preserve server logs in PR #710. Assuming it is merged, changes to run_tests.py in this PR aren't needed anymore.

2017-01-22 20:56 UTC, aaltat commented
Also this PR does not resolve the problem in Windows. The test execution still fails with or without this PR.

2017-01-22 21:10 UTC, HelioGuilherme66 commented
This PR was valid at the time it was proposed.

2017-01-22 21:49 UTC, aaltat commented
It could be that this is some sort of windows problem. If I comment out the `with http_server():` from `run_tests.py` and then run the `python -m SimpleHTTPServer 7000` I face similar issues then with the current http server implementation.

Having the support for running test in windows would be really nice, but it strongly looks like that we need to look some other http server.

2017-02-01 00:43 UTC, HelioGuilherme66 commented
Closing in favor of #748.
The send_header override was removed.

2017-02-01 00:43 UTC, closed without merging