issue #463
robotframework/SeleniumLibrary pull request #724
Opened 2016-12-30 11:58 UTC by Gaurang033

…ssue #463

table_cell_should_not_contain
table_column_should_not_contain
table_footer_should_not_contain
table_header_should_not_contain
table_row_should_not_contain
table_should_not_contain

2017-01-03 22:26 UTC, aaltat requested changes
In practice code in new keywords looks quite OK. There are some updates needed, but they do not need big refactoring. I did not read acceptance test, but I will read those in near future.

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +    def table_cell_should_not_contain(self, table_locator, row, column, expected, loglevel='INFO'):
For all the new code, try to follow pep8 maximum line length: https://www.python.org/dev/peps/pep-0008/#maximum-line-length. Fix in all places where it is exceeded in code which you have written. You do not need fix the existing code.

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +    def table_cell_should_not_contain(self, table_locator, row, column, expected, loglevel='INFO'):
Perhaps `expected` is not good argument name, because we expect that string is not there. Could `not_contain` or `value` be better argument names.

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +            raise AssertionError(message)
The exception text is not correct. It should say that: 
`Cell in table '%s' in row #%s and column #%s was not found `

But the text is correct for the exception in line 105.

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        except AssertionError, err:
Write: 
`except AssertionError as err:`
that is supported by Python 2 and Python 3

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        if element is not None:
It is more Python way to write: 
`if not element:`

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +                   % (col, table_locator, expected))
The indentation is not following pep8.

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +
Empty line is not needed.

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        if element is not None:
It is more Python way to write:
`if not element:`

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        if element is not None:
It is more Python way to write:
`if not element:`

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        if element is not None:
It is more Python way to write:
`if not element:`

2017-01-03 22:26 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        if element is not None:
It is more Python way to write:
`if not element:`

2017-01-03 22:32 UTC, aaltat commented
Also you can add your name to the https://github.com/robotframework/Selenium2Library/blob/master/BUILD.rst file if you want credit.

2017-01-04 07:54 UTC, Gaurang033 commented on src/Selenium2Library/keywords/_tableelement.py
> +    def table_cell_should_not_contain(self, table_locator, row, column, expected, loglevel='INFO'):
I have kept all the arguments name same as other functions in the file to keep the consistency, if like I can change that.

2017-01-04 08:56 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +    def table_cell_should_not_contain(self, table_locator, row, column, expected, loglevel='INFO'):
Please change only argument name only for new keywords. Changing the old ones would be backwards incompatible change and I am reluctant to do so.

2017-01-05 11:20 UTC, Gaurang033 commented
@aaltat I am not sure what you mean by the following comment. 

> Also you can add your name to the https://github.com/robotframework/Selenium2Library/blob/master/BUILD.rst file if you want credit.

2017-01-05 11:24 UTC, aaltat commented
You can add, if you want, your name to the file and short description what you have done.

2017-01-05 11:27 UTC, aaltat commented
Ah but the file was wrong, here the correct file https://github.com/robotframework/Selenium2Library/blob/master/CHANGES.rst

2017-01-05 11:29 UTC, Gaurang033 commented
@aaltat That's what I was wondering. Should I mentioned the changes under 1.8.1 or create the new section 1.8.2 and mentioned under that?

2017-01-05 11:34 UTC, aaltat commented
1.8.1 is the right one, it should actually say next release.

2017-01-11 10:44 UTC, Gaurang033 commented
@aaltat any idea when you are going to merge this request?

2017-01-11 10:47 UTC, aaltat commented
Is that TODO comment valid one?

2017-01-11 10:52 UTC, Gaurang033 commented
@aaltat No, not TODO. I was just excited to see my code merged so asked.

2017-01-11 11:17 UTC, aaltat commented
Could you remove the comment then? This week is busy but I hope that I time in the weekend to read the code

2017-01-29 15:13 UTC, aaltat requested changes
Could you remove the ToDo comment

2017-01-29 15:13 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        # TODO new message as per comment
This line indicates that PR is not ready.

2017-01-29 15:13 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        # TODO new message as per comment
Could you remove the comment, because it looks invalid

2017-02-01 21:06 UTC, aaltat commented
There are some comments for the test.

2017-02-01 21:06 UTC, aaltat requested changes

2017-02-01 21:06 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +        Verifies that a certain cell in a table does not contain `expected`.
Join lines 77 and 78 as a single line.

2017-02-01 21:06 UTC, aaltat commented on src/Selenium2Library/keywords/_tableelement.py
> +    def table_cell_should_not_contain(self, table_locator, row, column, value, loglevel='INFO'):
Following PEP8[1] is required, fix the line length. Fix only in places where you did provide new code. 

[1] https://www.python.org/dev/peps/pep-0008/

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    [Documentation]    Should Give Error Message When Content Found In Table
Do repeats what test name says and therefore it is not needed. Remove the documentation.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    [Documentation]    Verify Table Contains With CSS And XPath Locators
Remove documentation because it repeats the keyword name.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +Verify Table Does Contain With CSS And XPath Locators
Keyword does not have anything to do with the CSS or xpath locators. Better name for keyword could be: Table Should Not Contain keyword raises correct error when value is found from table.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +Should Give Error Message When Content Found In Table
Better test name could be: Table Should Not Contain keyword raises correct error when value is found from table

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${value} =    set variable    simpleTable_A2
Using the Set Variable only creates not required distraction for the test. It would be cleaner to write: 
```| Table Cell Should Not Contain | simpleTable | 1 | 1 | simpleTable_A2 |```

Also use keywords with Title Case

Fix in all new test cases.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    table cell should not contain    ${table}    ${row}    ${col}    ${value}
It might be good idea to add line which uses numbers, like: 
```
| Table Cell Should Not Contain | simpleTable | ${1} | ${1} | simpleTable_A2 |
| Table Cell Should Not Contain | simpleTable | ${1.0} | ${1.0} | simpleTable_A2 |
```

Also test when value is in table header and footer

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${err}=    Set Variable    Cell in table '${table}' in row #${row} and column #${col} was not found
Putting error message in variable is OK, because it makes the test more readable.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${value} =    set variable    simpleTable_A1
simpleTable_A1 is an exact match, right? Expand test partial text too, example when value is: `simple`, `_A1`, `Table`, `1`, `${1}` and `${1.0}`

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    formattedTable    äöü€&äöü€&
Is there value for table header and footer?

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${value} =    set variable    simpleTable_A1
Also add test when value is in table header and footer.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +Test Table Row Should Not Contain
Value is an exact match, right? Expand test partial text too. Also add test when value is in table header and footer.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${value} =    set variable    tableWithSingleHeader_A1
Value is an exact match, right? Expand test partial text too. Also add test when value is in table header and footer.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${value} =    set variable    simpleTable_B2
Value is an exact match, right? Expand test partial text too. Also add test when value is in table header and footer.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${value} =    set variable    tableWithSingleHeader_A1
Value is an exact match, right? Expand test partial text too. Also add test when value is in table header and footer.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    table header should not contain  ${table}    ${value}
Add test when value is table body and table footer but value is not in table header.

2017-02-01 21:06 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    table footer should not contain    ${table}    ${expected}
Add test where value is in table header and body.

2017-02-02 11:04 UTC, Gaurang033 commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    table footer should not contain    ${table}    ${expected}
The value *withHeadAndFoot_A1* is already in the body, should i just add one more verification where value is not in header and rename the test? or should I rename this test to verify that value is in body but not in footer and then add another test to verify where value is in footer but not in header?

2017-02-02 11:10 UTC, Gaurang033 commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    table header should not contain  ${table}    ${value}
the value is in the body. Should I rename this test case to reflect that and add new test case to verify when value is in footer but not in header? or should I rename this test case to reflect both condition where value is in body and footer but not in header and add verification. I can't do that with single value as there is not table where same value is in footer and body but not in header. if you like I can create a new table.

2017-02-02 11:12 UTC, Gaurang033 commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${value} =    set variable    tableWithSingleHeader_A1
The value is in the header, should I just rename the test case and add new where value is in footer? or modify this and add condition to verify when value is in footer.

2017-02-02 11:17 UTC, Gaurang033 commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    formattedTable    äöü€&äöü€&
yes, it's already present, it verifies for header, footer and body. 
```
    withHeadAndFoot    withHeadAndFoot_AH1
    withHeadAndFoot    withHeadAndFoot_B2
    withHeadAndFoot    withHeadAndFoot_CF1
```

2017-02-02 11:39 UTC, Gaurang033 commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    table cell should not contain    ${table}    ${row}    ${col}    ${value}
should I add a separate test and just add condition to this tests?

2017-02-08 21:18 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    formattedTable    äöü€&äöü€&
OK, no changes is needed for that one.

2017-02-08 21:18 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    table cell should not contain    ${table}    ${row}    ${col}    ${value}
What ever feels more natural for you do it.

2017-02-08 21:19 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    ${value} =    set variable    tableWithSingleHeader_A1
Use a way that feels the best for your. Both options are fine.

2017-02-08 21:24 UTC, aaltat commented on test/acceptance/keywords/tables/table_should_not_contain.robot
> +    table header should not contain  ${table}    ${value}
1) Create test when value is not in header, body or footer, like with `tidii` or something.
2) Test when value is in body (the current test)
3) Create test when value is in footer.

These test can be combined to one test if it feels natural to write test in such way.

2019-04-22 19:43 UTC, aaltat commented
Closing due inactivity.

2019-04-22 19:43 UTC, closed without merging