Add RF 3.0.1, 2.9.2 and 2.8.7 to Travis
robotframework/SeleniumLibrary pull request #754
Opened 2017-02-01 21:48 UTC by aaltat

We must also test with RF version we support. Updated Travis to
run test for different Robot Framework versions.

2017-02-01 21:53 UTC, aaltat commented
Fixes #751

2017-02-01 23:35 UTC, HelioGuilherme66 requested changes
We should consider using selenium==2.53.6 with firefox-esr-latest and not with chrome. I suspect that newer chrome does not work well with 2.53.6.

2017-02-01 23:35 UTC, HelioGuilherme66 commented on .travis.yml
> +  - pip install selenium==$ROBOTFRAMEWORK
This is wrong. It should be:
`pip install robotframework==$ROBOTFRAMEWORK`

2017-02-02 06:26 UTC, aaltat commented on .travis.yml
> +  - pip install selenium==$ROBOTFRAMEWORK
Should not play with my hobbies so late in the night and therefore make stupid mistakes like this. Good catch, will fix it.

2017-02-07 20:08 UTC, aaltat commented on .travis.yml
> +  - pip install selenium==$ROBOTFRAMEWORK
Done

2017-02-08 17:18 UTC, merged