Css keywords
robotframework/SeleniumLibrary pull request #775
Opened 2017-03-14 20:01 UTC by Alexspayne

This keyword was written in a fork (I didn't write it)

Issue #774

I wasn't sure if I should keep the comment about the author or not.
I kept it because it was in the original repo.

2017-03-14 20:26 UTC, aaltat requested changes
Fix the comments and write tests. At least write write following tests:
1) Write few test that verify happy path
2) Test where property does not contain expected value
3) Test where element does not contain the CSS property
4) Test where css property is a number. Considering also RF providing the number in different types: 5 versus ${5}
5) Test where CSS property contains multiple elements, like: https://www.w3schools.com/cssref/pr_border.asp

2017-03-14 20:26 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +    ######################################################################
Remove lines 58 - 64.

2017-03-14 20:26 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +	    value for the targeted `prop`.
Doc strings must follow pep256

2017-03-14 20:26 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +    def _check_element_css_value(self, locator, prop, expected):
Because this method is only used in the `Element Css Attribute Should Be` it might be better idea to move the code from here to the keyword.

2017-03-14 20:26 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +	value = element.value_of_css_property(prop)
Following pep8 is required, specially on the line length.

2017-03-14 20:26 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +	if (value != expected):
Parentheses are not needed.

2017-03-14 20:26 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +	    raise AssertionError("Element locator '%s' css property '%s' had a "\
ValueError could be better error class.

2017-03-14 23:00 UTC, Alexspayne commented
I agree with all the requested changes.  Thanks @aaltat for the review and the feedback.
I will make the recommended changes hopefully soon.

2017-03-18 09:46 UTC, aaltat commented
For the new keyword, the code change looks OK. But it is missing the tests, which is not OK.

Also it looks like you used a tool to fix pep8 related errors, which is good thing too. But one pull request should do only a one thing. Having multiple fixes/enhancement in a one pull request makes the review harder. You can leave it for now but could you remember in the future.

2017-03-19 12:19 UTC, Alexspayne commented
I agree, I'll keep that in mind.
I still plan on writing the tests but it will take a bit longer as I needed to get acquainted with the test guidelines and be able to run them.

2017-03-19 15:26 UTC, aaltat commented
It's​explained in here: https://github.com/robotframework/Selenium2Library/blob/master/CONTRIBUTING.md#code-contributions and in here: https://github.com/robotframework/Selenium2Library/blob/master/BUILD.rst#unit-and-acceptance-tests

If you are developing in Windows, it might be good idea rebase with master. There is commit in master which fixes the test server problems when running in Windows.

2017-03-27 06:30 UTC, aaltat commented
How is the test case writing going on?

2017-03-27 09:55 UTC, Alexspayne commented
I'm unstuck, but I haven't had time to work on them.  Work, school, competitions, and consulting have had me fully booked.

2017-05-17 17:08 UTC, aaltat commented
How is the test case writing going on?

2017-05-18 14:06 UTC, Alexspayne commented
I haven't had time to work on them directly, but I have written some tests for other new keywords not yet pulled.  So the learning part is done.  I'm still planning on adding the tests, I just don't know when it will happen.

2017-05-23 21:12 UTC, AlexanderWhitestone commented
I discovered some limitations.
If you set a color to a named value, Selenium won't necessarily read it as-is from the style sheet.  It may return the RGB value instead of the named value like 'darkblue.'
So I guess this is not going to work for colors for now.

2017-05-24 08:16 UTC, pekkaklarck commented
It could also be the browser transforming color names to RGB values. In that case the actual behavior could also depend on the browser.

2017-05-24 13:40 UTC, aaltat commented
Verifying CSS can be complicated and one can run into unexpected problems. But I think it's still a good keyword to have.

The next release is coming soonnish and it would be nice to get this in.

2017-05-24 14:56 UTC, Alexspayne commented
I'm about half done with the tests.  If the color values are browser specific, then I think that will have to be handled by the user of the keyword.  For now I won't test for colors values because it might require browser specific conditions and would be difficult to maintain.

2017-05-24 15:32 UTC, aaltat commented
Sounds good to me.

2017-06-26 17:48 UTC, aaltat commented
Have you found time to finish this PR?

2017-07-06 19:35 UTC, Alexspayne commented
Sorry for the delay. I just started a new job so I haven't been working on this.

2017-07-07 13:01 UTC, aaltat commented
No worries. Do you think that at some point you would have time to finish this PR?

2017-07-07 13:25 UTC, Alexspayne commented
Yes, I will have time at some point.

2018-09-28 19:35 UTC, AlexanderWhitestone commented
Do we still want this? I let this PR get really old and I want to know if i should try fixing it.

2018-09-28 19:58 UTC, aaltat commented
Welcome back after so long time.

The feature gets asked now and then in the community and therefore the keywords would be good addition to the library. And if I recall correctly, it was just missing few acceptance tests. 

If you have time and will to fix the PR, I am happy to review and merge it. The history should be cleaned tough. We usually do not use merge commit's and history should be clean. Which means that your commits should be on top of the commit's that are already in the master.

2018-10-02 18:37 UTC, Alexspayne commented
Yea I messed up the history while trying to pull in the latest.  I will work on it and do a proper rebase so the commits are on top.

2018-10-03 13:28 UTC, aaltat commented
No problems, take your time.

2019-04-22 19:42 UTC, aaltat commented
Are you still planning to work on the PR or can we close it?

2019-05-02 18:01 UTC, Alexspayne commented
We can close it.  I haven't been using the library and I'm not long familiar with it unfortunately.

2019-05-02 18:07 UTC, aaltat commented
I understand and now worries. Thanks for effort and if there is a need, it can be always found from the GitHub.

2019-05-02 18:07 UTC, closed without merging