New keyword `Should Be Focused` - WIP
robotframework/SeleniumLibrary pull request #855
Opened 2017-08-04 00:08 UTC by HelioGuilherme66

See issue #851.

WIP - because needs more positive tests for different types of elements

2017-08-04 08:31 UTC, aaltat requested changes
Looks pretty good, there are few things to consider.

2017-08-04 08:31 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +        New in SeleniumLibrary 2.0.1.
Next release will be 3.0.0, could you change the text accordingly.

2017-08-04 08:31 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +            raise AssertionError("Internal Error: '%s'" % (err))
Lines 229 - 232 could be replaced with this: https://github.com/SeleniumHQ/selenium/blob/fb6c35ed4974adc2c2f8308ee9d78fc4f6f3004a/py/selenium/webdriver/remote/switch_to.py#L34

2017-08-04 08:31 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +        if not element == focused:
if element != focused:

2017-08-04 08:31 UTC, aaltat commented on test/acceptance/keywords/element_focus.robot
> +# Suite Teardown    Close All Browsers
Is this line needed?

2017-08-04 08:31 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +            raise AssertionError("ERROR: Element '%s' is not with focus." % (locator))
Is the word `ERROR` needed in message?

2017-08-04 21:52 UTC, HelioGuilherme66 commented on src/Selenium2Library/keywords/element.py
> +            raise AssertionError("Internal Error: '%s'" % (err))
I have seen that proposal, but it is for Remote webdriver. It was not implemented, so the only alternative is to use JavaScript.

2017-08-04 21:54 UTC, HelioGuilherme66 commented on test/acceptance/keywords/element_focus.robot
> +# Suite Teardown    Close All Browsers
I won't be in the final version. I use it when running test file individually.

2017-08-04 22:51 UTC, aaltat commented on src/Selenium2Library/keywords/element.py
> +            raise AssertionError("Internal Error: '%s'" % (err))
Drivers inherits the remote, see the documentation example for the `Chrome`: http://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.chrome.webdriver

Also this works fine: 
```
from selenium import webdriver
from selenium.webdriver.remote.webelement import WebElement

driver = webdriver.Chrome()
driver.get('http://robotframework.org/')
focus = driver.switch_to.active_element
print isinstance(focus, WebElement)
print focus
driver.quit()
```
Please change the code to use the `driver.switch_to.active_element`

2017-08-12 19:49 UTC, aaltat approved these changes

2017-08-12 19:49 UTC, merged